name: bridge
description: Extensible end-to-end framework
author: Emil Persson <emil.n.persson@gmail.com>
version: 1.0.0-alpha7
homepage: http://github.com/dart-bridge/framework
environment:
  sdk: ">=1.12.0 <2.0.0"
dependencies:
  shelf: ">=0.5.7 <0.7.0"
  shelf_static: ">=0.2.2 <0.3.0"
  shelf_web_socket: '^0.0.1+2'
  yaml: ">=2.1.2 <3.0.0"
  cupid: '^0.9.0'
  dotenv: "^0.1.3+1"
  http_parser: '^0.0.2+6'
  formler: '^0.0.8'
  mongo_dart: '^0.1.47'
  dlog: '^0.0.5'
  plato: '>=0.2.0 <1.0.0'
  path: '^1.3.5'
  jaded: '^0.1.9'
  markdown: '^0.7.1+2'
  http_server: '^0.9.5+1'
  trestle: '>=0.5.0 <1.0.0'
dev_dependencies:
  test: any
  testcase: ">=0.1.0 <1.0.0"
  dart_coveralls: '^0.3.0'
